In [1]:
import numpy as np

# Create random number generator with seed for reproducibility
rng=np.random.default_rng(seed=42)

# Generate 30 random temperatures between 15 and 45
temps=rng.integers(15,45,size=30)

# Print full temperature array
print("Monthly temperatures:",temps)

# Calculate and print basic statistics
print("Mean:",np.mean(temps))
print("Max temp:",np.max(temps))
print("Min temp:",np.min(temps))

# Find index of hottest and coldest day using argmax and argmin
print(f"Hottest day: Day {np.argmax(temps)+1} with {np.max(temps)}°C")
print(f"Coldest day: Day {np.argmin(temps)+1} with {np.min(temps)}°C")

# Boolean indexing to filter temperatures above mean
print("Above average temps:",temps[temps>np.mean(temps)])

# Count days where temperature was below 25 using boolean sum
print("Days below 25°C:",np.sum(temps<25))

# Reshape 30 days into 5 weeks of 6 days each
weekly_temps=temps.reshape(5,6)
print("Weekly temps:",weekly_temps)

# Calculate mean of each week using axis=1 (row-wise)
print("Weekly averages:",np.mean(weekly_temps,axis=1))

# Normalize temperatures between 0 and 1 using min-max formula
normalized=(temps-np.min(temps))/(np.max(temps)-np.min(temps))
print("Normalized temps:",normalized)

# Filter temperatures between 30 and 40 using two conditions with & operator
print("Temps between 30 and 40:",temps[(temps>=30) & (temps<=40)])

Monthly temperatures: [17 38 34 28 27 40 17 35 21 17 30 44 37 37 36 38 30 18 40 28 30 26 20 42
 38 34 27 39 31 28]
Mean: 30.9
Max temp: 44
Min temp: 17
Hottest day: Day 12 with 44°C
Coldest day: Day 1 with 17°C
Above average temps: [38 34 40 35 44 37 37 36 38 40 42 38 34 39 31]
Days below 25°C: 6
Weekly temps: [[17 38 34 28 27 40]
 [17 35 21 17 30 44]
 [37 37 36 38 30 18]
 [40 28 30 26 20 42]
 [38 34 27 39 31 28]]
Weekly averages: [30.66666667 27.33333333 32.66666667 31.         32.83333333]
Normalized temps: [0.         0.77777778 0.62962963 0.40740741 0.37037037 0.85185185
 0.         0.66666667 0.14814815 0.         0.48148148 1.
 0.74074074 0.74074074 0.7037037  0.77777778 0.48148148 0.03703704
 0.85185185 0.40740741 0.48148148 0.33333333 0.11111111 0.92592593
 0.77777778 0.62962963 0.37037037 0.81481481 0.51851852 0.40740741]
Temps between 30 and 40: [38 34 40 35 30 37 37 36 38 30 40 30 38 34 39 31]
